services:
  app:
    build: .
    container_name: wwn-app
    ports:
      - "8081:8080"
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://admin:password@host.docker.internal:27017/wwn?authSource=admin
    networks:
      - wwn-network

networks:
  wwn-network:
    driver: bridge